name: array_object_adapter
description: >-
  Adapter that is similar to the ObjectAdapter (ArrayObjectAdapter) from the Android Leanback support library.
version: 1.0.1
homepage: https://github.com/mi-sch-ka
repository: https://github.com/mi-sch-ka/array-object-adapter
issue_tracker: https://github.com/mi-sch-ka/array-object-adapter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # reactive programming: additional capabilities to dart streams and stream-controllers.
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false